---
title: Configuration
description: Main part of amelioration process
privilege: TrustedInstaller
actions:
    # Sync time and set to more reliable time servers
  - !service: {name: "w32time", operation: start, ignoreErrors: true}
  - !run: {exe: 'w32tm', args: '/config /manualpeerlist:pool.ntp.org /syncfromflags:manual /update'}
  - !run: {exe: 'w32tm', args: '/resync'}
  
  - !run: {exe: 'manage-bde', args: '-off C:'}

  - !status: {status: 'Cleaning user interface'}
  - !service:
    name: "WpnService"
    operation: stop
    ignoreErrors: true
  - !service:
    name: "WpnUserService*"
    operation: stop
    ignoreErrors: true

  - !file:
    path: "%SYSTEMDRIVE%\\Users\\Public\\Desktop\\Microsoft Edge.lnk"
  - !file:
    path: "%ALLUSERSPROFILE%\\Microsoft\\Windows\\Start Menu\\Programs\\Accessories\\Windows Media Player.lnk"
  - !file:
    path: "%WINDIR%\\HelpPane.exe"
  - !file:
    path: "%WINDIR%\\SystemApps\\MicrosoftWindows.Client.Core_cw5n1h2txyewy\\SystemSettingsExtensions.dll"
  - !file:
    path: "%WINDIR%\\SystemApps\\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\\SystemSettingsExtensions.dll"

  - !run:
    exeDir: true
    exe: "CLEANUP.bat"
    weight: 30

  - !run: {exe: "explorer.exe", wait: false, runas: currentUser}

  - !status: {status: 'Configuring permissions', option: "security-enhanced"}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System', value: 'ConsentPromptBehaviorAdmin', type: REG_DWORD, data: '5', option: "security-enhanced"}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System', value: 'ConsentPromptBehaviorUser', type: REG_DWORD, data: '3', option: "security-enhanced"}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System', value: 'EnableInstallerDetection', type: REG_DWORD, data: '1', option: "security-enhanced"}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System', value: 'EnableLUA', type: REG_DWORD, data: '1', option: "security-enhanced"}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System', value: 'EnableVirtualization', type: REG_DWORD, data: '1', option: "security-enhanced"}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System', value: 'PromptOnSecureDesktop', type: REG_DWORD, data: '1', option: "security-enhanced"}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System', value: 'ValidateAdminCodeSignatures', type: REG_DWORD, data: '0', option: "security-enhanced"}
  - !registryValue: {path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System', value: 'FilterAdministratorToken', type: REG_DWORD, data: '0', option: "security-enhanced"}

  - !run:
    exeDir: true
    exe: "ADMIN.bat"
    weight: 10
    option: "security-enhanced"

  - !status: {status: 'Implementing SFC mitigation'}
  - !run:
    exeDir: true
    exe: "SFCDEPLOY.bat"
    weight: 5

  - !status: {status: 'Modifying login screen', option: "ui"}
  - !run:
    exeDir: true
    exe: "LOGIN.bat"
    option: "ui"